[tool.poetry]
name = "duplicates-finder-pack"
version = "1.0.0"
description = "Pack duplicates-finder find and count duplicates data"
authors = ["qalita"]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
qalita-core = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
